#!/bin/bash
# Tailscale Remote Access add-on module.
#
# This file is sourced by bootstrap.sh. Use return, not exit.

TAILSCALE_STATE_DIR="$HOME/.config/ai-bootstrap"
TAILSCALE_STATE_FILE="$TAILSCALE_STATE_DIR/tailscale.sh"
TAILSCALE_APP_PATH="${TAILSCALE_APP_PATH:-/Applications/Tailscale.app}"
TAILSCALE_APP_BIN="${TAILSCALE_APP_BIN:-/Applications/Tailscale.app/Contents/MacOS/tailscale}"
TAILSCALE_WRAPPER_PATH="${TAILSCALE_WRAPPER_PATH:-/usr/local/bin/tailscale}"
TAILSCALE_PKG_INDEX_URL="https://pkgs.tailscale.com/stable/"
TAILSCALE_PKG_URL=""
TAILSCALE_PKG_VERSION=""
TAILSCALE_TEAM_ID="W5364U7YZB"
TAILSCALE_BIN=""

tailscale_log_error() {
  log_error "$1"
}

tailscale_state_quote() {
  # Module-owned values are constrained to safe strings. Keep the writer simple
  # and reject any accidental single quote rather than writing risky shell.
  case "$1" in
    *"'"*) return 1 ;;
  esac
  printf "%s" "$1"
}

tailscale_now() {
  date -u +%FT%TZ
}

tailscale_load_state() {
  TAILSCALE_CT_SHOWN="${TAILSCALE_CT_SHOWN:-}"
  TAILSCALE_HOSTNAME="${TAILSCALE_HOSTNAME:-}"
  TAILSCALE_SERVE_URL="${TAILSCALE_SERVE_URL:-}"
  TAILSCALE_SETUP_AT="${TAILSCALE_SETUP_AT:-}"

  [ -f "$TAILSCALE_STATE_FILE" ] || return 0

  if [ -f "$BOOTSTRAP_DIR/lib/state_source_validation.sh" ]; then
    # shellcheck source=lib/state_source_validation.sh
    source "$BOOTSTRAP_DIR/lib/state_source_validation.sh"
    if ! state_validate_sourceable_file "$TAILSCALE_STATE_FILE"; then
      log_warn "Remote Access settings could not be read, so this run will refresh them."
      return 0
    fi
  fi

  # shellcheck disable=SC1090
  source "$TAILSCALE_STATE_FILE"
}

tailscale_write_state() {
  local hostname="$1"
  local serve_url="$2"
  local setup_at
  setup_at=$(tailscale_now)

  mkdir -p "$TAILSCALE_STATE_DIR" || return 1

  local q_hostname q_serve_url q_setup_at tmp_file
  q_hostname=$(tailscale_state_quote "$hostname") || return 1
  q_serve_url=$(tailscale_state_quote "$serve_url") || return 1
  q_setup_at=$(tailscale_state_quote "$setup_at") || return 1
  tmp_file="$TAILSCALE_STATE_FILE.tmp.$$"

  if ! cat >"$tmp_file" <<EOF; then
#!/bin/bash
# Generated by ai-dev-bootstrap-mac Remote Access setup.
# This file is overwritten when the Tailscale add-on is run.

export TAILSCALE_CT_SHOWN='1'
export TAILSCALE_HOSTNAME='$q_hostname'
export TAILSCALE_SERVE_URL='$q_serve_url'
export TAILSCALE_SETUP_AT='$q_setup_at'
EOF
    rm -f "$tmp_file"
    return 1
  fi

  mv "$tmp_file" "$TAILSCALE_STATE_FILE"
}

tailscale_preflight() {
  if ! command -v gum >/dev/null 2>&1; then
    tailscale_log_error "Remote Access needs gum before it can guide setup. Run the full installer first, then try Remote Access again."
    return 1
  fi

  if command_exists opencode; then
    return 0
  fi

  echo "Remote Access needs OpenCode first. I can run the full installer now, or stop here."
  local choice
  choice=$(ui_choose "Run full installer" "Exit")
  case "$choice" in
    "Run full installer")
      if ! command -v breadcrumb_write >/dev/null 2>&1; then
        # shellcheck source=lib/breadcrumb.sh
        source "$BOOTSTRAP_DIR/lib/breadcrumb.sh"
      fi
      breadcrumb_write tailscale || return 1
      unset BOOTSTRAP_MODULE_ONLY BOOTSTRAP_NONINTERACTIVE AI_BOOTSTRAP_NONINTERACTIVE
      exec "$BOOTSTRAP_DIR/bootstrap.sh"
      ;;
    *)
      return 1
      ;;
  esac
}

tailscale_sort_versions() {
  if sort -V </dev/null >/dev/null 2>&1; then
    sort -V
  else
    sort -t. -k1,1n -k2,2n -k3,3n
  fi
}

tailscale_select_pkg_version() {
  local index versions version

  TAILSCALE_PKG_VERSION=""
  TAILSCALE_PKG_URL=""

  if ! index=$(curl -fsSL "$TAILSCALE_PKG_INDEX_URL"); then
    tailscale_log_error "Tailscale versions could not be checked. Check your internet connection, then try again."
    return 1
  fi

  versions=$(printf "%s\n" "$index" \
    | grep -Eo 'Tailscale-[0-9]+[.][0-9]+[.][0-9]+-macos[.]pkg' \
    | sed -E 's/^Tailscale-//; s/-macos[.]pkg$//' \
    | sort -u)

  if [ -z "$versions" ]; then
    tailscale_log_error "Tailscale versions could not be found. Try Remote Access again in a few minutes."
    return 1
  fi

  version=$(printf "%s\n" "$versions" | tailscale_sort_versions | tail -n 1)
  if [ -z "$version" ]; then
    tailscale_log_error "Tailscale versions could not be sorted. Try Remote Access again in a few minutes."
    return 1
  fi

  TAILSCALE_PKG_VERSION="$version"
  TAILSCALE_PKG_URL="${TAILSCALE_PKG_INDEX_URL}Tailscale-${version}-macos.pkg"
}

tailscale_install_pkg() {
  if [ -d "$TAILSCALE_APP_PATH" ]; then
    log_skip "Tailscale is already installed"
    return 0
  fi

  local tmpfile signature
  tailscale_select_pkg_version || return 1

  tmpfile=$(mktemp "${TMPDIR:-/tmp}/tailscale.XXXXXX.pkg") || return 1

  if ! curl -fsSLo "$tmpfile" "$TAILSCALE_PKG_URL"; then
    rm -f "$tmpfile"
    tailscale_log_error "Tailscale $TAILSCALE_PKG_VERSION could not be downloaded. Check your internet connection, then try again."
    return 1
  fi

  if ! signature=$(pkgutil --check-signature "$tmpfile" 2>&1); then
    rm -f "$tmpfile"
    tailscale_log_error "The Tailscale $TAILSCALE_PKG_VERSION installer could not be verified, so setup stopped before installing it."
    return 1
  fi

  if [[ "$signature" != *"$TAILSCALE_TEAM_ID"* ]] || [[ "$signature" != *"Tailscale Inc"* ]]; then
    rm -f "$tmpfile"
    tailscale_log_error "The Tailscale $TAILSCALE_PKG_VERSION installer did not look like the official Tailscale installer, so setup stopped."
    return 1
  fi

  if ! sudo installer -pkg "$tmpfile" -target /; then
    rm -f "$tmpfile"
    tailscale_log_error "Tailscale $TAILSCALE_PKG_VERSION did not finish installing. Try Remote Access again after the installer window closes."
    return 1
  fi

  rm -f "$tmpfile"
  open "$TAILSCALE_APP_PATH" >/dev/null 2>&1 || true
  log_installed "Tailscale $TAILSCALE_PKG_VERSION installed"
}

tailscale_resolve_runtime_cli() {
  if command -v tailscale >/dev/null 2>&1; then
    TAILSCALE_BIN=$(command -v tailscale)
    return 0
  fi

  if [ -x "$TAILSCALE_APP_BIN" ]; then
    TAILSCALE_BIN="$TAILSCALE_APP_BIN"
    return 0
  fi

  tailscale_log_error "Tailscale is installed, but its command-line helper was not found. Open Tailscale once, then run Remote Access again."
  return 1
}

tailscale_wait_for_login() {
  local timeout_seconds="${TAILSCALE_WAIT_TIMEOUT_SECONDS:-300}"
  local start now status_output opened_app="0"
  start=$(date +%s)

  echo "Waiting for Tailscale sign-in. A browser or Tailscale window may ask you to finish signing in."
  while :; do
    status_output=$("$TAILSCALE_BIN" status 2>&1) && [[ "$status_output" != *"NeedsLogin"* ]] && return 0

    if [ "$opened_app" = "0" ]; then
      open "$TAILSCALE_APP_PATH" >/dev/null 2>&1 || true
      opened_app="1"
    fi

    now=$(date +%s)
    if [ $((now - start)) -ge "$timeout_seconds" ]; then
      tailscale_log_error "Tailscale sign-in did not finish in time. Open Tailscale, finish signing in, then run Remote Access again."
      return 1
    fi

    sleep 3
  done
}

tailscale_ensure_cli_wrapper() {
  if command -v tailscale >/dev/null 2>&1; then
    return 0
  fi

  if [ ! -x "$TAILSCALE_APP_BIN" ]; then
    tailscale_log_error "Tailscale is installed, but its command-line helper was not found."
    return 1
  fi

  local wrapper_dir
  wrapper_dir=$(dirname "$TAILSCALE_WRAPPER_PATH")
  if ! mkdir -p "$wrapper_dir" 2>/dev/null && ! sudo mkdir -p "$wrapper_dir"; then
    tailscale_log_error "Could not prepare the Tailscale command shortcut."
    return 1
  fi

  if ! printf '#!/bin/bash\nexec /Applications/Tailscale.app/Contents/MacOS/tailscale "$@"\n' | sudo tee "$TAILSCALE_WRAPPER_PATH" >/dev/null; then
    tailscale_log_error "Could not create the Tailscale command shortcut."
    return 1
  fi

  if ! sudo chmod +x "$TAILSCALE_WRAPPER_PATH"; then
    tailscale_log_error "Could not make the Tailscale command shortcut runnable."
    return 1
  fi

  log_installed "Tailscale command shortcut installed"
}

tailscale_magicdns_enabled() {
  local output="$1"
  [ -n "$output" ] || return 1

  if echo "$output" | grep -Eiq 'disabled|not enabled|off'; then
    return 1
  fi

  if echo "$output" | grep -Eiq 'MagicDNS:[[:space:]]*enabled|Search Domains|\.ts\.net|\.beta\.tailscale\.net'; then
    return 0
  fi

  return 1
}

tailscale_check_magicdns() {
  local dns_status
  dns_status=$("$TAILSCALE_BIN" dns status 2>/dev/null || true)

  if tailscale_magicdns_enabled "$dns_status"; then
    return 0
  fi

  echo "Remote Access needs Tailscale device names to be turned on. I will open the Tailscale settings page for you."
  open "https://login.tailscale.com/admin/dns" >/dev/null 2>&1 || true
  if ! ui_confirm "I've enabled MagicDNS. Continue?"; then
    return 1
  fi

  dns_status=$("$TAILSCALE_BIN" dns status 2>/dev/null || true)
  if tailscale_magicdns_enabled "$dns_status"; then
    return 0
  fi

  tailscale_log_error "MagicDNS still looks off. Turn it on in Tailscale, then run Remote Access again."
  return 1
}

tailscale_current_fqdn() {
  local fqdn
  fqdn=$("$TAILSCALE_BIN" status --json 2>/dev/null | jq -r '.Self.DNSName // empty' 2>/dev/null || true)
  fqdn=${fqdn%.}
  [ -n "$fqdn" ] || return 1
  printf "%s\n" "$fqdn"
}

tailscale_machine_from_fqdn() {
  local fqdn="$1"
  fqdn=${fqdn%.}
  printf "%s\n" "${fqdn%%.*}"
}

tailscale_hostname_valid() {
  local name="$1"
  [ ${#name} -le 63 ] || return 1
  [[ "$name" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]]
}

tailscale_prompt_hostname() {
  local current="$1"
  local entered
  entered=$(gum input --prompt "Device name: " --value "$current") || return 1
  if [ -z "$entered" ]; then
    entered="$current"
  fi
  printf "%s\n" "$entered"
}

tailscale_ct_and_hostname() {
  local fqdn current_name new_name tailnet_suffix
  fqdn=$(tailscale_current_fqdn || true)
  if [ -n "$fqdn" ]; then
    current_name=$(tailscale_machine_from_fqdn "$fqdn")
  else
    current_name="${TAILSCALE_HOSTNAME:-my-mac}"
  fi

  if [ "${TAILSCALE_CT_SHOWN:-}" != "1" ]; then
    gum style --border normal --padding "1" \
      "Remote Access may ask Tailscale for a private HTTPS address for this Mac. The device name you choose may appear in public certificate records. Pick a name you are comfortable seeing there."
  fi

  echo "Current device name: $current_name"

  while :; do
    new_name=$(tailscale_prompt_hostname "$current_name") || return 1
    if tailscale_hostname_valid "$new_name"; then
      break
    fi
    echo "Use lowercase letters, numbers, and hyphens only. Do not start or end with a hyphen. Keep it under 64 characters."
  done

  if [ "$new_name" != "$current_name" ]; then
    if ! "$TAILSCALE_BIN" set --hostname "$new_name"; then
      echo "Tailscale would not let me change the device name."
      if ! ui_confirm "Continue with the current device name?"; then
        return 1
      fi
      new_name="$current_name"
    else
      if [[ "$fqdn" == *.* ]]; then
        tailnet_suffix="${fqdn#*.}"
        fqdn="$new_name.$tailnet_suffix"
      else
        fqdn=$(tailscale_current_fqdn || true)
      fi
    fi
  fi

  TAILSCALE_HOSTNAME_RESULT="$new_name"
  TAILSCALE_FQDN_RESULT="${fqdn:-$new_name}"
  TAILSCALE_CT_SHOWN=1
}

tailscale_generate_password() {
  local had_pipefail=0 password
  if set -o | grep -q '^pipefail[[:space:]]*on'; then
    had_pipefail=1
  fi

  set +o pipefail
  password=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 40)
  if [ "$had_pipefail" -eq 1 ]; then
    set -o pipefail
  fi

  if [ ${#password} -ne 40 ]; then
    return 1
  fi
  printf "%s\n" "$password"
}

tailscale_prepare_password() {
  local password created="0"
  if password=$(security find-generic-password -s opencode-server-password -a "$USER" -w 2>/dev/null); then
    :
  else
    password=$(tailscale_generate_password) || {
      tailscale_log_error "Could not create the Remote Access password. Run Remote Access again."
      return 1
    }
    if ! security add-generic-password -s opencode-server-password -a "$USER" -w "$password" -T ""; then
      tailscale_log_error "Could not save the Remote Access password in Keychain."
      return 1
    fi
    created="1"
  fi

  if ! printf "%s" "$password" | pbcopy; then
    tailscale_log_error "Could not copy the Remote Access password to the clipboard."
    return 1
  fi
  TAILSCALE_PASSWORD_RESULT="$password"
  TAILSCALE_PASSWORD_CREATED="$created"
}

tailscale_deploy_scripts() {
  if [ -z "${AI_BOOTSTRAP_WORKSPACE:-}" ]; then
    tailscale_log_error "The saved workspace is missing. Run the full installer, then try Remote Access again."
    return 1
  fi

  local src="$BOOTSTRAP_DIR/scripts"
  local dest="$AI_BOOTSTRAP_WORKSPACE/scripts"
  local rc_src="$BOOTSTRAP_DIR/dotfiles/rc/tailscale.zsh"
  local rc_dest="$HOME/.config/ai-bootstrap/shell/rc/tailscale.zsh"
  local script_file

  if [ ! -d "$src" ]; then
    tailscale_log_error "Remote Access helper scripts are missing from this installer."
    return 1
  fi

  mkdir -p "$dest" || return 1
  if ! cp -R "$src/." "$dest/"; then
    tailscale_log_error "Could not copy the Remote Access helper scripts."
    return 1
  fi

  mkdir -p "$dest/personal" || return 1
  for script_file in "$dest/personal/"*.sh; do
    [ -f "$script_file" ] || continue
    chmod +x "$script_file"
  done

  if [ ! -f "$rc_src" ]; then
    tailscale_log_error "The Remote Access shell shortcuts are missing from this installer."
    return 1
  fi

  mkdir -p "$(dirname "$rc_dest")" || return 1
  cp "$rc_src" "$rc_dest"
}

tailscale_start_opencode_web() {
  local deployed_scripts="$AI_BOOTSTRAP_WORKSPACE/scripts"

  # shellcheck disable=SC1090,SC1091
  source "$deployed_scripts/lib/keychain.sh"
  # shellcheck disable=SC1090,SC1091
  source "$deployed_scripts/lib/opencode-daemon.sh"

  if opencode_daemon_pid_for_port 4096 >/dev/null 2>&1; then
    return 0
  fi

  OPENCODE_WEB_PORT=4096 OPENCODE_WEB_HOSTNAME=127.0.0.1 "$deployed_scripts/personal/opencode-web.sh" || return 1
  opencode_daemon_pid_for_port 4096 >/dev/null 2>&1
}

tailscale_serve_has_4096() {
  local status_json="$1"
  echo "$status_json" | grep -q '4096'
}

tailscale_start_serve() {
  local status_json
  status_json=$("$TAILSCALE_BIN" serve status --json 2>/dev/null || true)

  if ! tailscale_serve_has_4096 "$status_json"; then
    if ! "$TAILSCALE_BIN" serve --bg 4096; then
      tailscale_log_error "Tailscale could not turn on Remote Access."
      return 1
    fi
  fi

  status_json=$("$TAILSCALE_BIN" serve status --json 2>/dev/null || true)
  if ! tailscale_serve_has_4096 "$status_json"; then
    tailscale_log_error "Remote Access did not finish turning on. Try again in a moment."
    return 1
  fi
}

tailscale_success_screen() {
  local url="$1"
  local password="$2"
  local password_line

  if [ "${TAILSCALE_PASSWORD_CREATED:-0}" = "1" ]; then
    password_line="Password: $password"
  else
    password_line="Password: copied from Keychain to your clipboard. It is also shown here so you can save it on your phone: $password"
  fi

  open "$url" >/dev/null 2>&1 || true
  gum style --border normal --padding "1" \
    "Remote Access is ready.

Open this address from your Tailscale devices:
$url

Username: opencode
$password_line

After you sign in with Safari, you can save the password. iCloud Passwords can then offer it on your phone."
  if [ -t 0 ]; then
    echo "Press Enter when ready."
    read -r _tailscale_done || true
  fi
}

tailscale_module_main() {
  # The add-on is intentionally interactive, even when invoked from the module
  # fast path that marks normal modules as non-interactive.
  unset BOOTSTRAP_NONINTERACTIVE AI_BOOTSTRAP_NONINTERACTIVE

  tailscale_load_state

  tailscale_preflight || return 1
  tailscale_install_pkg || return 1
  tailscale_resolve_runtime_cli || return 1
  tailscale_wait_for_login || return 1
  tailscale_ensure_cli_wrapper || return 1
  tailscale_check_magicdns || return 1
  tailscale_ct_and_hostname || return 1
  tailscale_prepare_password || return 1
  tailscale_deploy_scripts || return 1
  tailscale_start_opencode_web || return 1
  tailscale_start_serve || return 1

  local serve_url
  serve_url="https://${TAILSCALE_FQDN_RESULT%.}"
  tailscale_success_screen "$serve_url" "$TAILSCALE_PASSWORD_RESULT"
  tailscale_write_state "$TAILSCALE_HOSTNAME_RESULT" "$serve_url" || return 1

  log_installed "Remote Access is ready"
}

tailscale_module_main
