#!/usr/bin/env bash
#
# Assembles a "Vibe Code.app" macOS app bundle from the source files in this
# directory. Branch F (launcher_improvement_plan.md §8): the bundle is built
# by `osacompile` from launch.applescript, then post-processed to swap in
# our curated Info.plist, piggy-bank icon, and the bash helper script that
# the AppleScript invokes.
#
# Bundle layout produced:
#
#   Vibe Code.app/
#     Contents/
#       Info.plist                          (curated; from launcher/Info.plist)
#       MacOS/applet                        (AppleScript runtime, from osacompile)
#       Resources/
#         VibeCode.icns                     (piggy-bank icon)
#         launch-helper.sh                  (the bash logic the AppleScript invokes)
#         Scripts/main.scpt                 (compiled AppleScript, from osacompile)
#         description.rtfd/                 (osacompile boilerplate; harmless)
#       _CodeSignature/                     (regenerated by codesign -s - after edits)
#       PkgInfo                             (osacompile output; left as-is)
#
# Why osacompile + post-process and NOT a hand-assembled bundle:
#   The Mach-O at Contents/MacOS/applet is the AppleScript runtime stub.
#   It's a universal binary distributed with macOS that we can't easily
#   reproduce. `osacompile` is the documented way to obtain it
#   (alternative: copy from /System/Library/CoreServices/, which is
#   fragile across macOS versions). We take osacompile's output and
#   override every identity-related field via plutil + cp + rm.
#
# Why we re-codesign at the end:
#   osacompile signs its output ad-hoc. Editing Info.plist or replacing
#   resource files invalidates the signature. Without re-signing, macOS
#   refuses to launch the bundle ("damaged and can't be opened"). We
#   re-sign with `codesign -s - --force --deep` — same ad-hoc identity,
#   no Apple Developer ID required.
#
# Why we delete Assets.car and applet.icns:
#   osacompile bakes a default icon into Resources/Assets.car AND drops
#   applet.icns at Resources/applet.icns. Modern macOS may prefer the
#   asset catalog over a loose .icns even when CFBundleIconFile points
#   elsewhere. Deleting both removes the ambiguity entirely; the only
#   icon in the bundle is then VibeCode.icns. See
#   launcher_improvement_plan.md §1.5.3 finding 1.
#
# Usage:  launcher/build.sh <output-dir>
#
# The output dir will contain "Vibe Code.app". Any pre-existing bundle of
# that name is replaced atomically.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <output-dir>" >&2
  exit 64
fi

dest_dir="$1"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APPLESCRIPT_SRC="$HERE/launch.applescript"
HELPER_SH="$HERE/launch-helper.sh"
INFO_PLIST="$HERE/Info.plist"
ICNS="$HERE/icon/VibeCode.icns"

for f in "$APPLESCRIPT_SRC" "$HELPER_SH" "$INFO_PLIST" "$ICNS"; do
  if [[ ! -f "$f" ]]; then
    echo "error: missing required file: $f" >&2
    exit 1
  fi
done

# osacompile and plutil must be on PATH. They ship with macOS but if
# someone runs this on a non-Mac (e.g. accidentally invoked from a Linux
# CI runner), fail loudly rather than silently producing a broken bundle.
for tool in osacompile plutil codesign; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: required tool not found on PATH: $tool" >&2
    echo "  Branch F requires macOS. See launcher_improvement_plan.md §8." >&2
    exit 1
  fi
done

mkdir -p "$dest_dir"

# Build into a staging dir, then atomically swap into place. Avoids leaving
# a half-built bundle if anything fails mid-build.
staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT

bundle="$staging/Vibe Code.app"

# 1. osacompile generates the bundle skeleton (Contents/MacOS/applet,
#    Contents/Resources/Scripts/main.scpt, Contents/Resources/applet.icns,
#    Contents/Resources/Assets.car, Contents/Info.plist with default
#    "applet" identity, Contents/PkgInfo, and an ad-hoc _CodeSignature).
#
#    `-s` is critical: it produces a STAY-OPEN applet. Without `-s`, the
#    AppleScript runtime exits as soon as `on run` returns — `on idle`
#    handlers are silently ignored, the Dock tile vanishes within a
#    second, and Branch F's entire branding goal is defeated. The
#    stay-open vs. one-shot distinction is set at compile time, not
#    runtime; an `on idle` handler in the source is necessary but not
#    sufficient. Empirically verified during Branch F implementation:
#    without `-s`, the bundle launches Ghostty correctly but the applet
#    process is gone from `ps` within 2 seconds.
#
#    osacompile prints "<path>: replacing existing signature" to stderr
#    on every invocation (it ad-hoc-signs the output internally). That's
#    cosmetic chatter we capture via temp file and only surface on
#    failure — keeps build.sh's own stderr clean for callers (the bats
#    suite asserts on `launcher_install`'s stdout, which catches stderr
#    leaks via `bats run`).
_osacompile_log="$(mktemp)"
if ! osacompile -s -o "$bundle" "$APPLESCRIPT_SRC" >"$_osacompile_log" 2>&1; then
  cat "$_osacompile_log" >&2 || true
  rm -f "$_osacompile_log"
  echo "error: osacompile failed" >&2
  exit 1
fi
rm -f "$_osacompile_log"

# 2. Overwrite Info.plist with the curated source of truth. plutil is not
#    strictly needed (we're replacing the file wholesale), but a final
#    `plutil -lint` confirms the file is valid before we ship.
cp "$INFO_PLIST" "$bundle/Contents/Info.plist"
plutil -lint "$bundle/Contents/Info.plist" >/dev/null

# 3. Resource swap. Piggy-bank icon replaces the default applet icon.
#    Drop the helper script into Resources/ alongside Scripts/main.scpt.
cp "$ICNS" "$bundle/Contents/Resources/VibeCode.icns"
cp "$HELPER_SH" "$bundle/Contents/Resources/launch-helper.sh"
chmod 755 "$bundle/Contents/Resources/launch-helper.sh"

# 4. Remove default-icon ambiguity (see header comment).
rm -f "$bundle/Contents/Resources/applet.icns"
rm -f "$bundle/Contents/Resources/Assets.car"

# 5. Re-sign. Plist edits + resource swaps invalidated osacompile's
#    original signature. `--force` overwrites the existing signature;
#    `--deep` recurses into the bundle (covers Scripts/main.scpt and any
#    nested signed components). `-s -` is ad-hoc — no Apple Developer ID.
#
#    codesign on macOS is chatty even on success ("$path: replacing
#    existing signature" goes to stderr) and that chatter does not respect
#    a simple `2>&1` redirect from the parent shell on some macOS builds —
#    we route via a temp file and only echo it on failure.
_codesign_log="$(mktemp)"
if ! codesign -s - --force --deep "$bundle" >"$_codesign_log" 2>&1; then
  echo "warning: codesign re-sign failed (non-fatal on dev machines, but" >&2
  echo "         Gatekeeper may refuse to launch on a fresh user's Mac)" >&2
  cat "$_codesign_log" >&2 || true
fi
rm -f "$_codesign_log"

# 6. Atomic-ish swap. macOS doesn't have rename-replace for directories,
#    so we delete + move; the window is small and the alternative
#    (in-place edit) risks leaving stale files behind.
final="$dest_dir/Vibe Code.app"
if [[ -d "$final" ]]; then
  rm -rf "$final"
fi
mv "$bundle" "$final"

# Touch the bundle so Finder/LaunchServices notices the new mtime and
# refreshes the icon cache. Without this, replacing an existing bundle
# can show the old icon until cache invalidation fires naturally.
touch "$final"

echo "built $final"
