#!/bin/bash
# Enriched-state writer: writes ~/.config/ai-bootstrap/state.sh with the
# full set of bootstrap-run metadata (workspace, tier, version, timestamps).
#
# Why a separate file from lib/workspace.sh:
#
#   The workspace anchor needs to land EARLY in bootstrap (right after the
#   workspace prompt) so the cdc alias and the .app launcher can find it
#   even if a later module fails. lib/workspace.sh::workspace_write_state
#   owns that early write and has the smallest possible surface area.
#
#   The enriched state — tier, version, last-run timestamp — only makes
#   sense AFTER all modules have run successfully. That's a different
#   responsibility, deserves its own function. Mixing them would force
#   the early call to know about (and pass dummy values for) fields that
#   don't exist yet.
#
# Storage format: same shell-sourceable file as workspace_write_state.
# Field-by-field: each is a separate `export VAR='value'` line. The single
# quotes are intentional — paths and tier names never contain quotes (we
# control all writes), and quoting prevents future shells from doing
# unintended expansion.
#
# Idempotency / preservation: state_write reads the existing state.sh first
# (if any) and preserves AI_BOOTSTRAP_FIRST_RUN_AT — that field should
# only be set on the very first run. AI_BOOTSTRAP_LAST_RUN_AT is updated
# every run.

# Source the project version constant.
# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/version.sh"

# ── state_now ──────────────────────────────────────────────────────────────
# Returns the current UTC timestamp in ISO 8601 format. Pure wrapper around
# `date -u`; exists so tests can override it via env to pin "now."
state_now() {
  if [ -n "${AI_BOOTSTRAP_NOW_OVERRIDE:-}" ]; then
    echo "$AI_BOOTSTRAP_NOW_OVERRIDE"
    return 0
  fi
  date -u +%FT%TZ
}

# ── state_read_field ───────────────────────────────────────────────────────
# Read a single var from a shell-sourceable state file without polluting the
# caller's environment. Echoes the value, returns 0 on success; returns 1
# if the file doesn't exist or the var is unset/empty.
#
# Args:
#   $1: state_file
#   $2: var_name (e.g. AI_BOOTSTRAP_FIRST_RUN_AT)
state_read_field() {
  local state_file="$1"
  local var_name="$2"

  if [ ! -f "$state_file" ]; then
    return 1
  fi

  local value
  value=$(
    # shellcheck disable=SC1090
    source "$state_file" 2>/dev/null
    # Indirect expansion: print the value of the var whose name is in $1.
    eval "echo \"\${${var_name}:-}\""
  )

  if [ -z "$value" ]; then
    return 1
  fi

  echo "$value"
  return 0
}

# ── state_write ────────────────────────────────────────────────────────────
# Write the enriched state file. Preserves first-run-at across bootstrap
# re-runs; updates last-run-at every time.
#
# Args:
#   $1: state_file  — absolute path
#   $2: workspace   — absolute, validated workspace path
#   $3: tier        — selected tier key (essential|recommended|complete|custom)
#
# Returns:
#   0  on success
#   1  on failure (parent dir or write error)
state_write() {
  local state_file="$1"
  local workspace="$2"
  local tier="$3"

  local state_dir
  state_dir=$(dirname "$state_file")
  if ! mkdir -p "$state_dir"; then
    echo "state_write: failed to create $state_dir" >&2
    return 1
  fi

  local now
  now=$(state_now)

  # Preserve first-run-at if already set; otherwise this run becomes the
  # first run.
  local first_run_at
  if first_run_at=$(state_read_field "$state_file" "AI_BOOTSTRAP_FIRST_RUN_AT"); then
    : # keep existing value
  else
    first_run_at="$now"
  fi

  local tmp_file="${state_file}.tmp.$$"
  if ! cat >"$tmp_file" <<EOF; then
#!/bin/bash
# Generated by ai-dev-bootstrap-mac. Edit at your own risk —
# this file is overwritten on every bootstrap run.
#
# Sourced by ~/.config/ai-bootstrap/shell/aliases.sh and read by
# other bootstrap modules to locate user assets.

export AI_BOOTSTRAP_WORKSPACE='$workspace'
export AI_BOOTSTRAP_TIER='$tier'
export AI_BOOTSTRAP_VERSION='$AI_BOOTSTRAP_VERSION'
export AI_BOOTSTRAP_FIRST_RUN_AT='$first_run_at'
export AI_BOOTSTRAP_LAST_RUN_AT='$now'
EOF
    rm -f "$tmp_file"
    echo "state_write: failed to write $tmp_file" >&2
    return 1
  fi

  if ! mv "$tmp_file" "$state_file"; then
    rm -f "$tmp_file"
    echo "state_write: failed to replace $state_file" >&2
    return 1
  fi

  return 0
}
